package net.engining.sccc.init.param.sccc;

import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import net.engining.pcx.cc.param.model.PostCode;
import net.engining.pcx.cc.param.model.enums.AdjustIndicator;
import net.engining.pcx.cc.param.model.enums.PostProcessor;
import net.engining.pg.parameter.ParameterFacility;
import net.engining.pg.support.init.ParameterInitializer;
@Service
public class PostCodeInit implements ParameterInitializer{

	@Autowired
	private ParameterFacility facility;
	
	@Override
	@Transactional
	public void init() throws Exception {
		for(PostCode pc : facility.getParameterMap(PostCode.class).values()){
			facility.removeParameter(PostCode.class, pc.postCode);
		}
		
		for(PostCode pc : getPostCodeList()){
			facility.addParameter(pc.postCode,pc);
		}
		
	}
	public List<PostCode> getPostCodeList(){
		List<PostCode> list = new ArrayList<PostCode>();
		
		PostCode pc = new PostCode();
		pc.postCode = "SC0001";
		pc.description = "额度增加";
		pc.shortDesc = "额度增加";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0002";
		pc.description = "额度减少";
		pc.shortDesc = "额度减少";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0003";
		pc.description = "短期贷款发放资金-联合";
		pc.shortDesc = "短期贷款发放资金-联合";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0004";
		pc.description = "短期贷款发放资金-独立";
		pc.shortDesc = "短期贷款发放资金-独立";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0005";
		pc.description = "中长期贷款发放资金-联合";
		pc.shortDesc = "中长期贷款发放资金-联合";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0006";
		pc.description = "中长期贷款发放资金-独立";
		pc.shortDesc = "中长期贷款发放资金-独立";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0007";
		pc.description = "利息计提-短期-M3以下";
		pc.shortDesc = "利息计提-短期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0008";
		pc.description = "利息计提-短期-M3以上";
		pc.shortDesc = "利息计提-短期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0009";
		pc.description = "利息计提-中长期-M3以下";
		pc.shortDesc = "利息计提-中长期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0010";
		pc.description = "利息计提-中长期-M3以上";
		pc.shortDesc = "利息计提-中长期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0011";
		pc.description = "罚息计收-短期-M3以下";
		pc.shortDesc = "罚息计收-短期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0012";
		pc.description = "罚息计收-短期-M3以上";
		pc.shortDesc = "罚息计收-短期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0013";
		pc.description = "罚息计收-中长期-M3以下";
		pc.shortDesc = "罚息计收-中长期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0014";
		pc.description = "罚息计收-中长期-M3以上";
		pc.shortDesc = "罚息计收-中长期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0015";
		pc.description = "短期正常类转关注类本金";
		pc.shortDesc = "短期正常类转关注类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0016";
		pc.description = "短期关注类转次级类本金";
		pc.shortDesc = "短期关注类转次级类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0017";
		pc.description = "短期次级类转可疑类本金";
		pc.shortDesc = "短期次级类转可疑类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0018";
		pc.description = "短期可疑类转损失类本金";
		pc.shortDesc = "短期可疑类转损失类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0019";
		pc.description = "中长期正常类转关注类本金";
		pc.shortDesc = "中长期正常类转关注类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0020";
		pc.description = "中长期关注类转次级类本金";
		pc.shortDesc = "中长期关注类转次级类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0021";
		pc.description = "中长期次级类转可疑类本金";
		pc.shortDesc = "中长期次级类转可疑类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0022";
		pc.description = "中长期可疑类转损失类本金";
		pc.shortDesc = "中长期可疑类转损失类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0023";
		pc.description = "逾期后利息结转-短期-M3以下";
		pc.shortDesc = "逾期后利息结转-短期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0024";
		pc.description = "逾期后利息结转-短期-M3以上";
		pc.shortDesc = "逾期后利息结转-短期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0025";
		pc.description = "逾期后利息结转-中长期-M3以下";
		pc.shortDesc = "逾期后利息结转-中长期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0026";
		pc.description = "逾期后利息结转-中长期-M3以上";
		pc.shortDesc = "逾期后利息结转-中长期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0027";
		pc.description = "溢缴款处理";
		pc.shortDesc = "发生溢缴款";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0028";
		pc.description = "溢缴款处理";
		pc.shortDesc = "溢缴款退回";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0029";
		pc.description = "提前还款手续费处理";
		pc.shortDesc = "提前还款手续费处理";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		//M0
		pc = new PostCode();
		pc.postCode = "SC0030";
		pc.description = "短期正常类贷款本金还款-联合";
		pc.shortDesc = "短期正常类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M1,M2,M3
		pc = new PostCode();
		pc.postCode = "SC0031";
		pc.description = "短期关注类贷款本金还款-联合";
		pc.shortDesc = "短期关注类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M4
		pc = new PostCode();
		pc.postCode = "SC0032";
		pc.description = "短期次级类贷款本金还款-联合";
		pc.shortDesc = "短期次级类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M5、M6
		pc = new PostCode();
		pc.postCode = "SC0033";
		pc.description = "短期可疑类贷款本金还款-联合";
		pc.shortDesc = "短期可疑类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M7
		pc = new PostCode();
		pc.postCode = "SC0034";
		pc.description = "短期损失类贷款本金还款-联合";
		pc.shortDesc = "短期损失类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M0
		pc = new PostCode();
		pc.postCode = "SC0035";
		pc.description = "短期正常类贷款本金还款-独立";
		pc.shortDesc = "短期正常类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M1,M2,M3
		pc = new PostCode();
		pc.postCode = "SC0036";
		pc.description = "短期关注类贷款本金还款-独立";
		pc.shortDesc = "短期关注类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M4
		pc = new PostCode();
		pc.postCode = "SC0037";
		pc.description = "短期次级类贷款本金还款-独立";
		pc.shortDesc = "短期次级类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M5、M6
		pc = new PostCode();
		pc.postCode = "SC0038";
		pc.description = "短期可疑类贷款本金还款-独立";
		pc.shortDesc = "短期可疑类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M7
		pc = new PostCode();
		pc.postCode = "SC0039";
		pc.description = "短期损失类贷款本金还款-独立";
		pc.shortDesc = "短期损失类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M0
		pc = new PostCode();
		pc.postCode = "SC0040";
		pc.description = "中长期正常类贷款本金还款-联合";
		pc.shortDesc = "中长期正常类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M1,M2,M3
		pc = new PostCode();
		pc.postCode = "SC0041";
		pc.description = "中长期关注类贷款本金还款-联合";
		pc.shortDesc = "中长期关注类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M4
		pc = new PostCode();
		pc.postCode = "SC0042";
		pc.description = "中长期次级类贷款本金还款-联合";
		pc.shortDesc = "中长期次级类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M5、M6
		pc = new PostCode();
		pc.postCode = "SC0043";
		pc.description = "中长期可疑类贷款本金还款-联合";
		pc.shortDesc = "中长期可疑类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M7
		pc = new PostCode();
		pc.postCode = "SC0044";
		pc.description = "中长期损失类贷款本金还款-联合";
		pc.shortDesc = "中长期损失类贷款本金还款-联合";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M0
		pc = new PostCode();
		pc.postCode = "SC0045";
		pc.description = "中长期正常类贷款本金还款-独立";
		pc.shortDesc = "中长期正常类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M1,M2,M3
		pc = new PostCode();
		pc.postCode = "SC0046";
		pc.description = "中长期关注类贷款本金还款-独立";
		pc.shortDesc = "中长期关注类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M4
		pc = new PostCode();
		pc.postCode = "SC0047";
		pc.description = "中长期次级类贷款本金还款-独立";
		pc.shortDesc = "中长期次级类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M5、M6
		pc = new PostCode();
		pc.postCode = "SC0048";
		pc.description = "中长期可疑类贷款本金还款-独立";
		pc.shortDesc = "中长期可疑类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//M7
		pc = new PostCode();
		pc.postCode = "SC0049";
		pc.description = "中长期损失类贷款本金还款-独立";
		pc.shortDesc = "中长期损失类贷款本金还款-独立";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0050";
		pc.description = "短期销项税";
		pc.shortDesc = "短期销项税";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0051";
		pc.description = "中长期销项税";
		pc.shortDesc = "中长期销项税";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0052";
		pc.description = "短期逾期后罚息结转";
		pc.shortDesc = "短期逾期后罚息结转";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0053";
		pc.description = "中长期逾期后罚息结转";
		pc.shortDesc = "中长期逾期后罚息结转";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0400";
		pc.description = "利息计提-短期";
		pc.shortDesc = "利息计提";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0401";
		pc.description = "利息计提-中长期";
		pc.shortDesc = "利息计提";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0402";
		pc.description = "销项税补记-短期-利息";
		pc.shortDesc = "销项税补记";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0403";
		pc.description = "销项税补记-中长期-利息";
		pc.shortDesc = "销项税补记";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0404";
		pc.description = "销项税补记-短期-罚息";
		pc.shortDesc = "销项税补记";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0405";
		pc.description = "销项税补记-中长期-罚息";
		pc.shortDesc = "销项税补记";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0406";
		pc.description = "逾期本金结转（转回）-关注类-短期";
		pc.shortDesc = "逾期本金结转（转回）-关注类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0407";
		pc.description = "逾期本金结转（转回）-次级类-短期";
		pc.shortDesc = "逾期本金结转（转回）-次级类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0408";
		pc.description = "逾期本金结转（转回）-可疑类-短期";
		pc.shortDesc = "逾期本金结转（转回）-可疑类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0409";
		pc.description = "逾期本金结转（转回）-损失类-短期";
		pc.shortDesc = "逾期本金结转（转回）-损失类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0410";
		pc.description = "逾期本金结转（转回）-关注类-中长期";
		pc.shortDesc = "逾期本金结转（转回）-关注类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0411";
		pc.description = "逾期本金结转（转回）-次级类-中长期";
		pc.shortDesc = "逾期本金结转（转回）-次级类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0412";
		pc.description = "逾期本金结转（转回）-可疑类-中长期";
		pc.shortDesc = "逾期本金结转（转回）-可疑类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0413";
		pc.description = "逾期本金结转（转回）-损失类-中长期";
		pc.shortDesc = "逾期本金结转（转回）-损失类";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0414";
		pc.description = "利息计提-短期-M3以下-冲正";
		pc.shortDesc = "利息计提-短期-M3以下-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0415";
		pc.description = "利息计提-短期-M1-M3-冲正";
		pc.shortDesc = "利息计提-短期-M1-M3-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0416";
		pc.description = "利息计提-短期-M3以上-冲正";
		pc.shortDesc = "利息计提-短期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0417";
		pc.description = "利息计提-中长期-M0-冲正";
		pc.shortDesc = "利息计提-中长期-M0-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0418";
		pc.description = "利息计提-中长期-M0_M3-冲正";
		pc.shortDesc = "利息计提-中长期-M0_M3-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0419";
		pc.description = "利息计提-中长期-M3以上-冲正";
		pc.shortDesc = "利息计提-中长期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0420";
		pc.description = "罚息计收-短期-M3（含）以下-冲正";
		pc.shortDesc = "罚息计收-短期-M3（含）以下-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0421";
		pc.description = "罚息计收-短期-M3以上-冲正";
		pc.shortDesc = "罚息计收-短期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0422";
		pc.description = "罚息计收-中长期-M3(含)以下-冲正";
		pc.shortDesc = "罚息计收-中长期-M3(含)以下-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0423";
		pc.description = "罚息计收-中长期-M3以上-冲正";
		pc.shortDesc = "罚息计收-中长期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0424";
		pc.description = "短期正常类转关注类本金-冲正";
		pc.shortDesc = "短期正常类转关注类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0425";
		pc.description = "短期关注类转次级类本金-冲正";
		pc.shortDesc = "短期关注类转次级类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0426";
		pc.description = "短期次级类转可疑类本金-冲正";
		pc.shortDesc = "短期次级类转可疑类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0427";
		pc.description = "短期可疑类转损失类本金-冲正";
		pc.shortDesc = "短期可疑类转损失类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0428";
		pc.description = "中长期正常类转关注类本金-冲正";
		pc.shortDesc = "中长期正常类转关注类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0429";
		pc.description = "中长期关注类转次级类本金-冲正";
		pc.shortDesc = "中长期关注类转次级类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0430";
		pc.description = "中长期次级类转可疑类本金-冲正";
		pc.shortDesc = "中长期次级类转可疑类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0431";
		pc.description = "中长期可疑类转损失类本金-冲正";
		pc.shortDesc = "中长期可疑类转损失类本金-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0432";
		pc.description = "逾期后利息结转-短期-M3以下-冲正";
		pc.shortDesc = "逾期后利息结转-短期-M3以下-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0433";
		pc.description = "逾期后利息结转-短期-M3以上-冲正";
		pc.shortDesc = "逾期后利息结转-短期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0434";
		pc.description = "逾期后利息结转-中长期-M3以下-冲正";
		pc.shortDesc = "逾期后利息结转-中长期-M3以下-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0435";
		pc.description = "逾期后利息结转-中长期-M3以上-冲正";
		pc.shortDesc = "逾期后利息结转-中长期-M3以上-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC0436";
		pc.description = "短期逾期后罚息结转-冲正";
		pc.shortDesc = "短期逾期后罚息结转-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC0437";
		pc.description = "中长期逾期后罚息结转-冲正";
		pc.shortDesc = "中长期逾期后罚息结转-冲正";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//拿去花
		pc = new PostCode();
		pc.postCode = "SC050";
		pc.description = "额度增加";
		pc.shortDesc = "额度增加";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC051";
		pc.description = "额度减少";
		pc.shortDesc = "额度减少";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC054";
		pc.description = "短期贷款发放资金";
		pc.shortDesc = "短期贷款发放资金";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC055";
		pc.description = "短期正常类贷款本金还款";
		pc.shortDesc = "短期正常类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC056";
		pc.description = "短期关注类贷款本金还款";
		pc.shortDesc = "短期关注类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC057";
		pc.description = "短期次级类贷款本金还款";
		pc.shortDesc = "短期次级类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC058";
		pc.description = "短期可疑类贷款本金还款";
		pc.shortDesc = "短期可疑类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC059";
		pc.description = "短期损失类贷款本金还款";
		pc.shortDesc = "短期损失类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);

		pc = new PostCode();
		pc.postCode = "SC052";
		pc.description = "贷款归还";
		pc.shortDesc = "分期手续费还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC053";
		pc.description = "违约金还款";
		pc.shortDesc = "违约金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC060";
		pc.description = "转分期";
		pc.shortDesc = "转分期";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		//中银
		pc = new PostCode();
		pc.postCode = "SC001";
		pc.description = "短期贷款发放资金";
		pc.shortDesc = "短期贷款发放资金";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC018";
		pc.description = "中长期贷款发放资金";
		pc.shortDesc = "中长期贷款发放资金";
		pc.blkcdCheckInd = Boolean.TRUE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC002";
		pc.description = "利息计提-短期-M3以下";
		pc.shortDesc = "利息计提-短期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC003";
		pc.description = "利息计提-短期-M3以上";
		pc.shortDesc = "利息计提-短期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC019";
		pc.description = "利息计提-中长期-M3以下";
		pc.shortDesc = "利息计提-中长期-M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC020";
		pc.description = "利息计提-中长期-M3以上";
		pc.shortDesc = "利息计提-中长期-M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC005";
		pc.description = "短期正常类转关注类本金";
		pc.shortDesc = "短期正常类转关注类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC006";
		pc.description = "短期关注类转次级类本金";
		pc.shortDesc = "短期关注类转次级类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC007";
		pc.description = "短期次级类转可疑类本金";
		pc.shortDesc = "短期次级类转可疑类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC008";
		pc.description = "短期可疑类转损失类本金";
		pc.shortDesc = "短期可疑类转损失类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC022";
		pc.description = "中长期正常类转关注类本金";
		pc.shortDesc = "中长期正常类转关注类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC023";
		pc.description = "中长期关注类转次级类本金";
		pc.shortDesc = "中长期关注类转次级类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC024";
		pc.description = "中长期次级类转可疑类本金";
		pc.shortDesc = "中长期次级类转可疑类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC025";
		pc.description = "中长期可疑类转损失类本金";
		pc.shortDesc = "中长期可疑类转损失类本金";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC009";
		pc.description = "逾期后利息结转-短期";
		pc.shortDesc = "逾期后利息结转-短期";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC026";
		pc.description = "逾期后利息结转-中长期";
		pc.shortDesc = "逾期后利息结转-中长期";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.FALSE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = false;
		list.add( pc );
		
		pc = new PostCode();
		pc.postCode = "SC010";
		pc.description = "短期正常类贷款本金还款";
		pc.shortDesc = "短期正常类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC011";
		pc.description = "短期关注类贷款本金还款";
		pc.shortDesc = "短期关注类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC012";
		pc.description = "短期次级类贷款本金还款";
		pc.shortDesc = "短期次级类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC013";
		pc.description = "短期可疑类贷款本金还款";
		pc.shortDesc = "短期可疑类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC014";
		pc.description = "短期损失类贷款本金还款";
		pc.shortDesc = "短期损失类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC015";
		pc.description = "短期M3以下利息还款";
		pc.shortDesc = "短期M3以下利息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC016";
		pc.description = "短期M3以上利息还款";
		pc.shortDesc = "短期M3以上利息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC017";
		pc.description = "罚息还款";
		pc.shortDesc = "罚息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC027";
		pc.description = "中长期正常类贷款本金还款";
		pc.shortDesc = "中长期正常类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC028";
		pc.description = "中长期关注类贷款本金还款";
		pc.shortDesc = "中长期关注类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC029";
		pc.description = "中长期次级类贷款本金还款";
		pc.shortDesc = "中长期次级类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC030";
		pc.description = "中长期可疑类贷款本金还款";
		pc.shortDesc = "中长期可疑类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC031";
		pc.description = "中长期损失类贷款本金还款";
		pc.shortDesc = "中长期损失类贷款本金还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC032";
		pc.description = "中长期M3以下利息还款";
		pc.shortDesc = "中长期M3以下利息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC033";
		pc.description = "中长期M3以上利息还款";
		pc.shortDesc = "中长期M3以上利息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC034";
		pc.description = "罚息还款";
		pc.shortDesc = "罚息还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC035";
		pc.description = "贷款归还";
		pc.shortDesc = "收取其他费用还款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC037";
		pc.description = "息费减免-短期-M3以下";
		pc.shortDesc = "短期减免利息M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC038";
		pc.description = "息费减免-短期-M3以上";
		pc.shortDesc = "短期减免利息M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC039";
		pc.description = "息费减免-短期";
		pc.shortDesc = "短期减免罚息";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC040";
		pc.description = "息费减免-中长期-M3以下";
		pc.shortDesc = "中长期减免利息M3以下";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC041";
		pc.description = "息费减免-中长期-M3以上";
		pc.shortDesc = "中长期减免利息M3以上";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC042";
		pc.description = "息费减免-中长期";
		pc.shortDesc = "中长期减免罚息";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.DN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC043";
		pc.description = "息费返还";
		pc.shortDesc = "返还利息";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC044";
		pc.description = "息费返还";
		pc.shortDesc = "返回罚息";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC036";
		pc.description = "息费返还";
		pc.shortDesc = "返还其他费用";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC004";
		pc.description = "短期罚息计收";
		pc.shortDesc = "短期罚息计收";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC021";
		pc.description = "中长期罚息计收";
		pc.shortDesc = "中长期罚息计收";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC045";
		pc.description = "短期关注类贷款转正常";
		pc.shortDesc = "短期关注类贷款转正常";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "SC046";
		pc.description = "中长期关注类贷款转正常";
		pc.shortDesc = "中长期关注类贷款转正常";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		//商户清算
		pc = new PostCode();
		pc.postCode = "S0001";
		pc.description = "商户清算资金划款（代付款项）";
		pc.shortDesc = "代付款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0002";
		pc.description = "商户清算资金收款（代收款项）";
		pc.shortDesc = "代收款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0003";
		pc.description = "联合贷参与方清算资金划款（还款款项）";
		pc.shortDesc = "参与方还款款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0004";
		pc.description = "联合贷参与方清算资金收款（放款款项）";
		pc.shortDesc = "参与方放款款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0005";
		pc.description = "联合贷代理方清算资金收款（放款款项）";
		pc.shortDesc = "代理方放款款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0006";
		pc.description = "联合贷代理方清算资金划款（还款款项）";
		pc.shortDesc = "代理方还款款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0007";
		pc.description = "商户清算资金暂缓划付（支付通路）";
		pc.shortDesc = "支付通路";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0008";
		pc.description = "商户清算资金暂缓划付（联合贷）";
		pc.shortDesc = "联合贷";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0009";
		pc.description = "商户清算资金暂缓划付（手续费及分润款项）";
		pc.shortDesc = "手续费及分润款项";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0010";
		pc.description = "联合贷代理方清算资金划款（利息返还）";
		pc.shortDesc = "利息返还";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0011";
		pc.description = "联合贷代理方清算资金划款（费用返还）";
		pc.shortDesc = "费用返还";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0012";
		pc.description = "商户清算资金重新发起划付";
		pc.shortDesc = "商户清算资金重新发起划付";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0013";
		pc.description = "清算短款挂账";
		pc.shortDesc = "清算短款挂账";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0014";
		pc.description = "清算长款挂账";
		pc.shortDesc = "清算长款挂账";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0015";
		pc.description = "商户请款（放款短款）";
		pc.shortDesc = "放款短款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0016";
		pc.description = "商户退单（放款长款）";
		pc.shortDesc = "放款长款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0017";
		pc.description = "商户请款（还款/退货短款）";
		pc.shortDesc = "还款/退货短款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0018";
		pc.description = "商户退单（还款/退货长款）";
		pc.shortDesc = "还款/退货长款";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0019";
		pc.description = "商户分润款项划付";
		pc.shortDesc = "商户分润款项划付";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
		pc = new PostCode();
		pc.postCode = "S0020";
		pc.description = "商户分润款项划付";
		pc.shortDesc = "商户分润款项划付";
		pc.blkcdCheckInd = Boolean.FALSE;
		pc.stmtInd = Boolean.TRUE;
		pc.adjustInd = AdjustIndicator.B;
		pc.processor = PostProcessor.CN;
		pc.subAcctType = "";
		pc.isReversal = false;
		pc.isAccounting = true;
		list.add(pc);
		
//		//商户清算
//		pc = new PostCode();
//		pc.postCode = "Q0001";
//		pc.description = "商户清算资金划款";
//		pc.shortDesc = "代付款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0002";
//		pc.description = "商户清算资金收款";
//		pc.shortDesc = "代收款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0003";
//		pc.description = "联合贷参与方清算资金划款";
//		pc.shortDesc = "还款款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0004";
//		pc.description = "联合贷参与方清算资金收款";
//		pc.shortDesc = "放款款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0005";
//		pc.description = "联合贷代理方清算资金划款";
//		pc.shortDesc = "放款款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0006";
//		pc.description = "联合贷代理方清算资金收款";
//		pc.shortDesc = "还款款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0007";
//		pc.description = "商户清算资金暂缓划付";
//		pc.shortDesc = "支付通路";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0008";
//		pc.description = "商户清算资金暂缓划付";
//		pc.shortDesc = "联合贷";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0009";
//		pc.description = "商户清算资金暂缓划付";
//		pc.shortDesc = "手续费及分润款项";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0010";
//		pc.description = "商户清算资金重新发起划付";
//		pc.shortDesc = "商户清算资金重新发起划付";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0011";
//		pc.description = "清算短款挂账";
//		pc.shortDesc = "清算短款挂账";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0012";
//		pc.description = "清算长款挂账";
//		pc.shortDesc = "清算长款挂账";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0013";
//		pc.description = "商户请款";
//		pc.shortDesc = "放款短款";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0014";
//		pc.description = "客户请款（放款短款-放款补录）-短期";
//		pc.shortDesc = "放款补录-短期";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0015";
//		pc.description = "客户请款（放款短款-放款补录）-中长期";
//		pc.shortDesc = "放款补录-中长期";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0016";
//		pc.description = "客户请款（放款短款-放款补录）-短期-联合";
//		pc.shortDesc = "放款补录-短期-联合";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0017";
//		pc.description = "客户请款（放款短款-放款补录）-中长期-联合";
//		pc.shortDesc = "放款补录-中长期-联合";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0018";
//		pc.description = "客户退单";
//		pc.shortDesc = "放款长款";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0019";
//		pc.description = "客户退单（放款长款-撤销贷款）-短期";
//		pc.shortDesc = "撤销贷款-短期";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0020";
//		pc.description = "客户退单（放款长款-撤销贷款）-中长期";
//		pc.shortDesc = "撤销贷款-中长期";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0021";
//		pc.description = "客户退单（放款长款-撤销贷款）-短期-联合";
//		pc.shortDesc = "撤销贷款-短期-联合";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0022";
//		pc.description = "客户退单（放款长款-撤销贷款）-中长期-联合";
//		pc.shortDesc = "撤销贷款-中长期-联合";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0023";
//		pc.description = "客户退单（放款长款-补代付）";
//		pc.shortDesc = "放款长款-补代付";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0024";
//		pc.description = "客户请款（还款/退货短款）";
//		pc.shortDesc = "还款/退货短款";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0025";
//		pc.description = "客户退单（还款/退货长款）";
//		pc.shortDesc = "还款/退货长款";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0026";
//		pc.description = "客户退单（还款/退货长款-还款补录）-短期-M0";
//		pc.shortDesc = "还款补录-短期-M0";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0027";
//		pc.description = "客户退单（还款/退货长款-还款补录）-短期-M1、M2、M3";
//		pc.shortDesc = "还款补录-短期-M1、M2、M3";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0028";
//		pc.description = "客户退单（还款/退货长款-还款补录）-短期-M4";
//		pc.shortDesc = "还款补录-短期-M4";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0029";
//		pc.description = "客户退单（还款/退货长款-还款补录）-短期-M5、M6";
//		pc.shortDesc = "还款补录-短期-M5、M6";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0030";
//		pc.description = "客户退单（还款/退货长款-还款补录）-短期-M7";
//		pc.shortDesc = "还款补录-短期-M7";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0031";
//		pc.description = "客户退单（还款/退货长款-还款补录）-中长期-M0";
//		pc.shortDesc = "还款补录-中长期-M0";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0032";
//		pc.description = "客户退单（还款/退货长款-还款补录）-中长期-M1、M2、M3";
//		pc.shortDesc = "还款补录-中长期-M1、M2、M3";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0033";
//		pc.description = "客户退单（还款/退货长款-还款补录）-中长期-M4";
//		pc.shortDesc = "还款补录-中长期-M4";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0034";
//		pc.description = "客户退单（还款/退货长款-还款补录）-中长期-M5、M6";
//		pc.shortDesc = "还款补录-中长期-M5、M6";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0035";
//		pc.description = "客户退单（还款/退货长款-还款补录）-中长期-M7";
//		pc.shortDesc = "还款补录-中长期-M7";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0036";
//		pc.description = "客户分润款项划付";
//		pc.shortDesc = "客户分润款项划付";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
//		
//		pc = new PostCode();
//		pc.postCode = "Q0037";
//		pc.description = "支付通路结算手续费款项划付";
//		pc.shortDesc = "支付通路结算手续费款项划付";
//		pc.blkcdCheckInd = Boolean.FALSE;
//		pc.stmtInd = Boolean.TRUE;
//		pc.adjustInd = AdjustIndicator.B;
//		pc.processor = PostProcessor.CN;
//		pc.subAcctType = "";
//		pc.isReversal = false;
//		pc.isAccounting = true;
//		list.add(pc);
		
		
		
		
		return list;
	}

}
