DROP INDEX IDX_JOBEXEID ON BATCH_STEP_EXECUTION;
DROP INDEX IDX_JOBEXEID_PARAMS ON BATCH_JOB_EXECUTION_PARAMS;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS DROP FOREIGN KEY JOB_EXEC_PARAMS_FK;

CREATE INDEX IDX_JOBEXEID ON BATCH_STEP_EXECUTION (JOB_EXECUTION_ID ASC);
CREATE INDEX IDX_JOBEXEID_PARAMS ON BATCH_JOB_EXECUTION_PARAMS (JOB_EXECUTION_ID ASC);